# Generated by Architecture Cosmos / KosmoAsset
# Blender sandbox script. Use only in a copied .blend sandbox file.
# It creates review collections/material placeholders and never saves or opens project files.

KOSMO_SANDBOX_ONLY = True
ALLOW_SCENE_WRITE = True

SANDBOX_ASSET = {
  "collection_name": "KOSMO_SANDBOX/warm-concrete-material-001",
  "import_mode": "create_material_from_parameters",
  "material_name": "KOSMO_MAT_warm-concrete-material-001",
  "source_file": "examples/kosmo-assets/kosmo-asset-demo/assets/materials/warm-concrete.material.json",
  "layer_names": [
    "material/base_color",
    "material/roughness",
    "material/metallic",
    "material/specular",
    "blender/principled_bsdf",
    "archicad/material/concrete/review"
  ]
}


def _collection(name, parent=None):
    collection = bpy.data.collections.get(name) or bpy.data.collections.new(name)
    if parent:
        if collection.name not in [child.name for child in parent.children]:
            parent.children.link(collection)
    elif collection.name not in [child.name for child in bpy.context.scene.collection.children]:
        bpy.context.scene.collection.children.link(collection)
    return collection


def _empty(name, collection):
    obj = bpy.data.objects.get(name) or bpy.data.objects.new(name, None)
    if obj.name not in collection.objects:
        try:
            collection.objects.link(obj)
        except RuntimeError:
            pass
    return obj


def run():
    print("KosmoAsset Blender sandbox")
    print(f"- asset: {SANDBOX_ASSET['collection_name']}")
    if not KOSMO_SANDBOX_ONLY or not ALLOW_SCENE_WRITE:
        print("Sandbox disabled. No scene objects created.")
        return
    try:
        global bpy
        import bpy
    except ModuleNotFoundError:
        print("Run this script inside Blender Python. No changes made in system Python.")
        return

    root = _collection("KOSMO_SANDBOX")
    asset_collection = _collection(SANDBOX_ASSET["collection_name"], root)
    for layer_name in SANDBOX_ASSET.get("layer_names", []):
        layer_collection = _collection(layer_name, asset_collection)
        _empty(f"{layer_name}/review_anchor", layer_collection)

    material_name = SANDBOX_ASSET.get("material_name")
    if material_name and not bpy.data.materials.get(material_name):
        material = bpy.data.materials.new(material_name)
        material.diffuse_color = (0.72, 0.62, 0.48, 1.0)

    print("Created review-only sandbox collections/material placeholders.")
    print("No file was opened, saved, uploaded or published.")


if __name__ == "__main__":
    run()
