# Generated by Architecture Cosmos / KosmoAsset
# Review-only Blender handoff. It does not modify the scene unless ALLOW_SCENE_WRITE is set to True.

ALLOW_SCENE_WRITE = False

ASSETS = [
  {
    "id": "warm-concrete-material-001",
    "title": "Warm Concrete Study Material",
    "collection_name": "KOSMO_ASSET/material/warm-concrete-material-001",
    "import_mode": "create_material_from_parameters",
    "material_name": "KOSMO_MAT_warm-concrete-material-001",
    "source_file": "examples/kosmo-assets/kosmo-asset-demo/assets/materials/warm-concrete.material.json",
    "layer_names": [
      "material/base_color",
      "material/roughness",
      "material/metallic",
      "material/specular",
      "blender/principled_bsdf",
      "archicad/material/concrete/review"
    ],
    "approved_for_import": False
  },
  {
    "id": "generic-column-glb-001",
    "title": "Generic Column GLB Slot",
    "collection_name": "KOSMO_ASSET/structure/generic-column-glb-001",
    "import_mode": "link_glb_as_collection",
    "material_name": None,
    "source_file": "examples/kosmo-assets/kosmo-asset-demo/assets/models/generic-column-glb-001.glb",
    "layer_names": [
      "structure/column_core_round",
      "structure/base_plate_reference",
      "structure/top_plate_reference",
      "analysis/axis_x",
      "analysis/axis_z",
      "KOSMO_COLUMN_FOOTPRINT",
      "KOSMO_COLUMN_CLEARANCE",
      "KOSMO_AXIS",
      "KOSMO_TEXT"
    ],
    "approved_for_import": False
  }
]


def run():
    print("KosmoAsset Blender handoff")
    for asset in ASSETS:
        print(f"- {asset['title']}: {asset['import_mode']} -> {asset['collection_name']}")
        if not asset.get("approved_for_import"):
            print("  review gate: not approved for production import")
    if not ALLOW_SCENE_WRITE:
        print("Review-only mode. Set ALLOW_SCENE_WRITE = True only inside an approved smoke-test file.")
        return
    import bpy
    for asset in ASSETS:
        collection = bpy.data.collections.get(asset["collection_name"]) or bpy.data.collections.new(asset["collection_name"])
        if collection.name not in [child.name for child in bpy.context.scene.collection.children]:
            try:
                bpy.context.scene.collection.children.link(collection)
            except TypeError:
                pass
        if asset.get("material_name") and not bpy.data.materials.get(asset["material_name"]):
            bpy.data.materials.new(asset["material_name"])


if __name__ == "__main__":
    run()
