const germanDisplayReplacements: Array<[RegExp, string]> = [
  [/\bPraehistorisch/g, 'Prähistorisch'],
  [/\bpraehistorisch/g, 'prähistorisch'],
  [/\bFrueh/g, 'Früh'],
  [/\bfrueh/g, 'früh'],
  [/\bGefuege\b/g, 'Gefüge'],
  [/\bGefueges\b/g, 'Gefüges'],
  [/\bgefuege\b/g, 'gefüge'],
  [/\bverknuepft\b/g, 'verknüpft'],
  [/\bverknuepfen\b/g, 'verknüpfen'],
  [/\bVerknuepfung\b/g, 'Verknüpfung'],
  [/\bgehoert\b/g, 'gehört'],
  [/\bgehoeren\b/g, 'gehören'],
  [/\bSpaeter\b/g, 'Später'],
  [/\bspaeter\b/g, 'später'],
  [/\bKoennen\b/g, 'Können'],
  [/\bkoennen\b/g, 'können'],
  [/\bPlaene\b/g, 'Pläne'],
  [/\bPlaenen\b/g, 'Plänen'],
  [/\bplaene\b/g, 'pläne'],
  [/\bGebaeude\b/g, 'Gebäude'],
  [/\bGebaeudes\b/g, 'Gebäudes'],
  [/\bGebaeuden\b/g, 'Gebäuden'],
  [/\bgebaeude\b/g, 'gebäude'],
  [/\bRaeumlich/g, 'Räumlich'],
  [/\braeumlich/g, 'räumlich'],
  [/\bHaeuslichkeit\b/g, 'Häuslichkeit'],
  [/\bhaeuslichkeit\b/g, 'häuslichkeit'],
  [/\bOeffentlich/g, 'Öffentlich'],
  [/\boeffentlich/g, 'öffentlich'],
  [/\bFuer\b/g, 'Für'],
  [/\bfuer\b/g, 'für'],
  [/\bUeber/g, 'Über'],
  [/\bueber/g, 'über'],
  [/\bPruef/g, 'Prüf'],
  [/\bpruef/g, 'prüf'],
  [/\bgeprueft\b/g, 'geprüft'],
  [/\bMuessen\b/g, 'Müssen'],
  [/\bmuessen\b/g, 'müssen'],
  [/\bWaehrend\b/g, 'Während'],
  [/\bwaehrend\b/g, 'während'],
  [/\bLaesst\b/g, 'Lässt'],
  [/\blaesst\b/g, 'lässt'],
  [/\bGroesser\b/g, 'Grösser'],
  [/\bgroesser\b/g, 'grösser'],
  [/\bAeltere\b/g, 'Ältere'],
  [/\baeltere\b/g, 'ältere'],
  [/\bMoeglich/g, 'Möglich'],
  [/\bmoeglich/g, 'möglich'],
  [/\bStaerker\b/g, 'Stärker'],
  [/\bstaerker\b/g, 'stärker'],
  [/\bschaerfen\b/g, 'schärfen'],
  [/\bNaechst/g, 'Nächst'],
  [/\bnaechst/g, 'nächst'],
  [/\bErschliessung\b/g, 'Erschliessung']
];

export function prettifyGermanText(text: string | null | undefined) {
  if (!text) return '';

  return germanDisplayReplacements.reduce((value, [pattern, replacement]) => value.replace(pattern, replacement), text);
}
