# Generated by Architecture Cosmos / KosmoAsset
# Review-only Blender handoff. It does not modify the scene unless ALLOW_SCENE_WRITE is set to True.

ALLOW_SCENE_WRITE = False

ASSETS = [
  {
    "id": "villa-savoye-concrete-frame-material-001",
    "title": "Villa Savoye Concrete Frame Material Study",
    "collection_name": "KOSMO_ASSET/material/villa-savoye-concrete-frame-material-001",
    "import_mode": "create_material_from_parameters",
    "material_name": "KOSMO_MAT_villa-savoye-concrete-frame-material-001",
    "source_file": None,
    "layer_names": [],
    "approved_for_import": False
  },
  {
    "id": "sogn-benedetg-wood-shingle-material-001",
    "title": "Sogn Benedetg Wood Shingle Material Study",
    "collection_name": "KOSMO_ASSET/material/sogn-benedetg-wood-shingle-material-001",
    "import_mode": "create_material_from_parameters",
    "material_name": "KOSMO_MAT_sogn-benedetg-wood-shingle-material-001",
    "source_file": None,
    "layer_names": [],
    "approved_for_import": False
  },
  {
    "id": "ingenbohl-mineral-pigment-material-001",
    "title": "Ingenbohl Mineral Pigment Material Study",
    "collection_name": "KOSMO_ASSET/material/ingenbohl-mineral-pigment-material-001",
    "import_mode": "create_material_from_parameters",
    "material_name": "KOSMO_MAT_ingenbohl-mineral-pigment-material-001",
    "source_file": None,
    "layer_names": [],
    "approved_for_import": False
  },
  {
    "id": "ingenbohl-concrete-core-frame-study-001",
    "title": "Ingenbohl Concrete Core and Frame Study",
    "collection_name": "KOSMO_ASSET/structure/ingenbohl-concrete-core-frame-study-001",
    "import_mode": "metadata_only",
    "material_name": None,
    "source_file": None,
    "layer_names": [],
    "approved_for_import": False
  }
]


def run():
    print("KosmoAsset Blender handoff")
    for asset in ASSETS:
        print(f"- {asset['title']}: {asset['import_mode']} -> {asset['collection_name']}")
        if not asset.get("approved_for_import"):
            print("  review gate: not approved for production import")
    if not ALLOW_SCENE_WRITE:
        print("Review-only mode. Set ALLOW_SCENE_WRITE = True only inside an approved smoke-test file.")
        return
    import bpy
    for asset in ASSETS:
        collection = bpy.data.collections.get(asset["collection_name"]) or bpy.data.collections.new(asset["collection_name"])
        if collection.name not in [child.name for child in bpy.context.scene.collection.children]:
            try:
                bpy.context.scene.collection.children.link(collection)
            except TypeError:
                pass
        if asset.get("material_name") and not bpy.data.materials.get(asset["material_name"]):
            bpy.data.materials.new(asset["material_name"])


if __name__ == "__main__":
    run()
